### ISSUE TITLE
how to use it? any tutorial?

### ISSUE THREAD

**Issue by pokjnb** [Unity-Technologies/NativeAudioPlugins#10]
I guess this SDK can be import as C++ dll in C# script? like  Dllimport[...], or add dll in plugin folder?  but this repo is like a project? how to install this SDK? download this repo and copy to unity projects？ don't get it..

basic question, hope get the answer...

**Comment by AlexxUnity** [comment]
Hey @pokjnb, first sorry for the very late response. We have some docs over [here](https://docs.unity3d.com/2023.3/Documentation/Manual/AudioMixerNativeAudioPlugin.html)

Basically the easiest way to get going with the example plugins provided here is to clone the repo, open up one of the projects (VisualStudio or Xcode in the NativeCode folder) and build. You then import the build lib into the unity plugin folder and you should see the list of demo plugins when adding effects to the AudioMixer.

Hope this helps.

**Comment by tastez** [comment]
Hi - is there a list of what export targets are supported and why? For example I assume WEBGL is NOT supported but i would like to know why.

**Comment by AlexxUnity** [comment]
Hey @tastez , Every build target should be supported. With the exception of webgl, which you already pointed out. I will make a ticket for us to look at explicitly stating this in the Native Audio Plugin docs somewhere. 

As for why no webgl support https://docs.unity3d.com/6000.0/Documentation/Manual/webgl-audio.html. Basically we can not use our internal audio engine (FMOD) on the web without serious work, which sadly the team does not have much bandwidth for at the moment. So we instead hand off the audio graph to the browser. This comes with the downside that lots of audio features are not possible.

hope this helps!

**Comment by AlexxUnity** [comment]
@pokjnb I am going to close this now, if you have more questions just open another issue or ask away on the forums https://forum.unity.com/forums/audio-video.74/

**Comment by AlexxUnity** [comment]
@pokjnb I am going to close this now, if you have more questions just open another issue or ask away on the forums https://forum.unity.com/forums/audio-video.74/
