### ISSUE TITLE
XCode project needs to be updated

### ISSUE THREAD

**Issue by Tak** [Unity-Technologies/NativeAudioPlugins#8]
> I am getting this when building: unsealed contents present in the bundle root
> Command CodeSign failed with a nonzero exit code

See https://stackoverflow.com/questions/25950544/codesign-what-are-unsealed-contents

**Comment by cerkut** [comment]
I erased the AudioPluginDemo.bundle under /Assets/Plugins then recompiled. It creates the AudioPluginDemo.bundle without this cryptic messages on M1 (after changing the BaseSDK, archs, etc in the project).  Hope this helps.

**Comment by AlexxUnity** [comment]
Should be good after merging #13 (hey @cerkut !)
